// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application";
import ErrorController from "./error_controller";
import TripPreviewController from "./trip_preview_controller";
import MapPickerController from "./map_picker_controller";
import VolunteerDndController from "./volunteer_dnd_controller";
import DropdownController from "./dropdown_controller";

application.register("error", ErrorController);
application.register("trip-preview", TripPreviewController);
application.register("map-picker", MapPickerController);
application.register("volunteer-dnd", VolunteerDndController);
application.register("dropdown", DropdownController);
