// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application";
import ErrorController from "./error_controller";
import TripPreviewController from "./trip_preview_controller";
import TripFormController from "./trip_form_controller";

application.register("error", ErrorController);
application.register("trip-preview", TripPreviewController);
application.register("trip-form", TripFormController);
