# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33bc67b20f8b79a5604c376f3076de2fc6753412cf6e7fe3bdf1f60428e5457ec6ef75a903ccba400b22e92638d7cf8705d206aae8feda9daeb43cf61ff4adf

test:
  secret_key_base: 73527dbffe1988810895c367de64e8e553ae704ff57d807fce71790019054fa3c52b80cd7ff71592eb252ab27b9a5a2ef7691243e99a84b993fff465e43378be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
