name: Build and Deploy to Fargate Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run_application_tests:
    uses: ./.github/workflows/application-tests.yml
    secrets: inherit

  build_and_push_server:
    uses: ./.github/workflows/deployment-staging.yml
    needs: run_application_tests
    secrets: inherit
