on: workflow_call

env:
  CONTAINER_NAME: app
  ECS_TASK_DEFINITION: .aws/task-definition-production.json

jobs:
  build_and_push:
    name: Build and push container
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.GH_OIDC_ROLE_ARN}}
        aws-region: ${{vars.AWS_REGION}}

    - name: Fetch secrets from AWS Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ${{secrets.SECRETS_ARN}}
        parse-json-secrets: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & tag
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg REACT_GTM_ID=${{env.PRODUCTION_ZUPA_REACT_GTM_ID}} --build-arg REACT_API_BASE_URL=${{env.PRODUCTION_ZUPA_REACT_API_BASE_URL}} -t $ECR_REGISTRY/${{ vars.APP_NAME }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ vars.APP_NAME }}:latest .

    - name: Push image to Amazon ECR
      id: push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push $ECR_REGISTRY/${{ vars.APP_NAME }}:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/${{ vars.APP_NAME }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Prepare task definition with environment values
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        sed -i 's|{{ECR_REGISTRY}}|${{ env.ECR_REGISTRY }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{APP_NAME}}|${{ vars.APP_NAME }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{AWS_LOG_GROUP}}|${{ vars.AWS_LOG_GROUP }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{AWS_REGION}}|${{ vars.AWS_REGION }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{SECRETS_ARN}}|${{ secrets.SECRETS_ARN }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{EXECUTION_ROLE_ARN}}|${{ secrets.EXECUTION_ROLE_ARN }}|g' ${{ env.ECS_TASK_DEFINITION }}
        sed -i 's|{{TASK_ROLE_ARN}}|${{ secrets.TASK_ROLE_ARN }}|g' ${{ env.ECS_TASK_DEFINITION }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.push-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ vars.APP_NAME }}
        cluster: ${{ vars.ECS_CLUSTER }}
        wait-for-service-stability: true
